apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    db: postgres
data:
  # TODO: this data should not be exposed, to change for secret claimer in k8s
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    db: postgres
spec:
  ports:
    - port: 5432
  selector:
    db: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      db: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-config
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: postgres-pv-claim
      nodeSelector:
        clusterLayer: db
